version: '3.9'

services:
  db:
    image: postgres:latest
    container_name: money_transfer_db
    restart: always

    environment:
      POSTGRES_DB: money_transfer
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"