spring:
  application:
    name: MoneyTransferApi
  datasource:
    url: jdbc:postgresql://localhost:5432/money_transfer
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
  liquibase:
    enabled: true

  security:
    jwt:
      secret-key-access: 3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b
      expiration-time-access: 3600000